[package]
name = "dashmap"
version = "3.2.2"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/dashmap"
homepage = "https://github.com/xacrimon/dashmap"
description = "Blazing fast concurrent HashMap for Rust."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[dependencies]
crossbeam-epoch = "0.8.0"
qadapt-spin = "1.0.1"
rustc-hash = "1.0.1"

[package.metadata.docs.rs]
all-features = true
