[package]
name = "dashmap"
version = "3.2.2"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/xacrimon/dashmap"
homepage = "https://github.com/xacrimon/dashmap"
description = "Blazing fast concurrent HashMap for Rust."
readme = "README.md"
documentation = "https://docs.rs/dashmap"
keywords = ["atomic", "concurrent", "hashmap"]
categories = ["concurrency", "algorithms", "data-structures"]

[dependencies]
crossbeam-epoch = "0.8.0"
spin = "0.5.2"
array-init = "0.1.1"

[dev-dependencies]
criterion = "0.3.0"
rayon = "1.2.1"
num_cpus = "1.12.0"

[[bench]]
name = "dashmap"
harness = false

[package.metadata.docs.rs]
all-features = true
